stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  tags: 
    - shell
  stage: build
  script:
    - echo "Compiling the code..."
    - docker build -t express:updated .
    - docker tag express:updated localhost:5000/express:updated
    - docker push localhost:5000/express:updated
    - echo "Compile complete."

deploy-job:      # This job runs in the deploy stage.
  variables:
    CI_DEBUG_TRACE: "true"
  stage: deploy  # It only runs when the build stage completes successfully (we don't do tests here, because we're just THAT confident everything will work as expected and why shouldn't it, right?)
  script:
    - echo "Deploying application..."
    - kubectl apply -f deployment.yaml
    - echo "Application successfully deployed."
