apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-nightly-deployment
  labels:
    app: express-nightly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-nightly
  template:
    metadata:
      labels:
        app: express-nightly
    spec:
      containers:
      - name: express
        image: localhost:5000/express:nightly
        ports:
        - containerPort: 3000
          name: "web"
---
apiVersion: v1
kind: Service
metadata:
  name: express-nightly-service
spec:
  selector:
    app: express-nightly
  ports:
    - protocol: TCP
      port: 80
      targetPort: "web"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-nightly-ingress
spec:
  rules:
  - host: express-nightly.localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: express-nightly-service
            port:
              number: 80
